{
  "name": "greeting-config",
  "profiles": [
     "default"
  ],
  "label": "master",
  "propertySources": [ 
      {
         "name":  "https://github.com/rdmullpiv/app-config.git/greeting-config.yml",
	 "source":  {
            "security.basic.enabled":  false,
            "management.security.enabled":  false	
         }
      }
  ]
}
