--- 
label: master
name: greeting-config
profiles: 
  - default
propertySources: 
  - 
    logging: 
      level: 
        io: 
          pivotal: INFO
    name: "https://github.com/rdmullpiv/app-config.git/greeting-config.yml"
    source: 
      management.security.enabled: false
      security.basic.enabled: false
